# 配置服务器端口
server:
  port: 8080
#  配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #注意这里是mysql5的驱动，如果是mysql8选择另一个
    username: root
    password: root
#    这里的url别忘记填写数据库名
    url: jdbc:mysql://localhost:3306/sun?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  application:
    name: user-center #这个名字一般是用来做微服务的服务名，用来标识某个服务的，与项目名保持一致即可
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)